// Firebase configuration generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFcg0o-plaNTl1MFl2Ush4_zxrOVmJMM',
    appId: '1:1053984490600:android:1cd420d02c7adeafe8a7dd',
    messagingSenderId: '1053984490600',
    projectId: 'zerolevelinginc',
    storageBucket: 'zerolevelinginc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoayvhq5FKuN4jiOGGRMY174ppYeoVAmA',
    appId: '1:1053984490600:ios:0c014d5e3583f17de8a7dd',
    messagingSenderId: '1053984490600',
    projectId: 'zerolevelinginc',
    storageBucket: 'zerolevelinginc.firebasestorage.app',
    iosBundleId: 'com.zeroapp.zero',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Rzcz0mos6ZOf9iY059bHgu2pWi0GltI',
    appId: '1:1053984490600:web:a253a3635fb6b4a9e8a7dd',
    messagingSenderId: '1053984490600',
    projectId: 'zerolevelinginc',
    authDomain: 'zerolevelinginc.firebaseapp.com',
    storageBucket: 'zerolevelinginc.firebasestorage.app',
    measurementId: 'G-C5V9CE1KRB',
  );

}